services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand({ ping: 1 })\" || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/smart-home
    working_dir: /app
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env

volumes:
  mongo_data:
